version: 2
# Tell CircleCI to use this workflow
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - "upstream-dev"
      - "python-3.6"
      - "python-3.7"
      - "python-3.8"
  default:
    jobs:
      - "upstream-dev"
      - "python-3.6"
      - "python-3.7"
      - "python-3.8"

shared: &shared
  steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          conda env create -f ${ENV_FILE}
          conda activate test_env_cmip6_preprocessing
          python -m pip install .
    - run:
        name: List packages in the current environment (base)
        command: |
          conda list
    - run:
        name: Running Tests
        command: |
          pytest -n 4 --junitxml=test-reports/junit.xml --cov=./ --verbose
        no_output_timeout: 30m
    - run:
        name: Uploading code coverage report
        command: |
          codecov
    - store_test_results:
        path: test-reports

    - store_artifacts:
        path: test-reports


jobs:
  "upstream-dev":
    <<: *shared
    environment:
      ENV_FILE: "./ci/environment-py37-upstream-master.yml"

  "python-3.6":
    <<: *shared
    environment:
      ENV_FILE: "./ci/environment-py36.yml"

  "python-3.7":
    <<: *shared
    environment:
      ENV_FILE: "./ci/environment-py37.yml"

  "python-3.8":
    <<: *shared
    environment:
      ENV_FILE: "./ci/environment-py38.yml"
