name: test_env_cmip6_preprocessing
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pyproj
  - matplotlib
  - cartopy
  - codecov
  - pytest-cov
  - black
  - numpy
  - cftime
  - dask
  - pip
  - pip:
    - pytest-xdist
    - git+https://github.com/mathause/regionmask.git
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/pandas-dev/pandas.git
    - git+https://github.com/xgcm/xgcm.git
