name: test_env_cmip6_preprocessing
channels:
  - conda-forge
dependencies:
  - python=3.8
  - xarray
  - numpy
  - pandas
  - intake-esm==2020.08.15 #temporary solution see https://github.com/intake/intake-esm/issues/305
  - zarr
  - xgcm
  - pyproj
  - matplotlib
  - regionmask # this will fail until the current version is released on conda
  - black
  - pytest-cov
  - pytest-xdist
  - codecov
  - cftime
