name: test_env_cmip6_preprocessing
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - numpy
  - pandas
  - intake-esm==2020.08.15 #temporary solution see https://github.com/intake/intake-esm/issues/305
  - xgcm
  - pyproj
  - matplotlib
  - cftime
  - pip
  - pip:
    - codecov
    - pytest-cov
    - pytest-xdist
    - black
