name: test_env_cmip6_preprocessing
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - numpy
  - pandas
  - intake
  - intake-esm
  - xgcm
  - pyproj
  - matplotlib
  - pip
  - pip:
    - codecov
    - pytest-cov
    - pytest-xdist
    - black
