name: cmip6_preprocessing-docs
dependencies:
  - python
  - future
  - pytest
  - numpydoc
  - sphinx
  - ipykernel
  - pip
  - pip:
    - docrep
    - nbsphinx
    - sphinx_pangeo_theme
    - jupyter_client
    - jupyter-sphinx